#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v23
# autospec commit: a88ffdc
#
Name     : gtk-layer-shell
Version  : 0.9.1
Release  : 2
URL      : https://github.com/wmww/gtk-layer-shell/archive/v0.9.1/gtk-layer-shell-0.9.1.tar.gz
Source0  : https://github.com/wmww/gtk-layer-shell/archive/v0.9.1/gtk-layer-shell-0.9.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0 MIT
Requires: gtk-layer-shell-data = %{version}-%{release}
Requires: gtk-layer-shell-lib = %{version}-%{release}
Requires: gtk-layer-shell-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(gobject-introspection-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : vala
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# GTK Layer Shell (GTK3 version)
__This project is complete and in maintenance mode.__ It will continue to receive fixes and updates to new GTK3 versions for the foreseeable future, but minimal development beyond that. New fetures will only be merged if they are critical for existing apps and don't threaten stability. New projects are recommended to use GTK4 instead.

%package data
Summary: data components for the gtk-layer-shell package.
Group: Data

%description data
data components for the gtk-layer-shell package.


%package dev
Summary: dev components for the gtk-layer-shell package.
Group: Development
Requires: gtk-layer-shell-lib = %{version}-%{release}
Requires: gtk-layer-shell-data = %{version}-%{release}
Provides: gtk-layer-shell-devel = %{version}-%{release}
Requires: gtk-layer-shell = %{version}-%{release}

%description dev
dev components for the gtk-layer-shell package.


%package lib
Summary: lib components for the gtk-layer-shell package.
Group: Libraries
Requires: gtk-layer-shell-data = %{version}-%{release}
Requires: gtk-layer-shell-license = %{version}-%{release}

%description lib
lib components for the gtk-layer-shell package.


%package license
Summary: license components for the gtk-layer-shell package.
Group: Default

%description license
license components for the gtk-layer-shell package.


%prep
%setup -q -n gtk-layer-shell-0.9.1
cd %{_builddir}/gtk-layer-shell-0.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744038880
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/gtk-layer-shell
cp %{_builddir}/gtk-layer-shell-%{version}/LICENSE_GPL.txt %{buildroot}/usr/share/package-licenses/gtk-layer-shell/31a3d460bb3c7d98845187c716a30db81c44b615 || :
cp %{_builddir}/gtk-layer-shell-%{version}/LICENSE_LGPL.txt %{buildroot}/usr/share/package-licenses/gtk-layer-shell/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
cp %{_builddir}/gtk-layer-shell-%{version}/LICENSE_MIT.txt %{buildroot}/usr/share/package-licenses/gtk-layer-shell/657f3d1be67d6bd8b79692c3b22fed1d44c443c3 || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GtkLayerShell-0.1.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/gtk-layer-shell-0.deps
/usr/share/vala/vapi/gtk-layer-shell-0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/gtk-layer-shell/gtk-layer-shell.h
/usr/lib64/libgtk-layer-shell.so
/usr/lib64/pkgconfig/gtk-layer-shell-0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgtk-layer-shell.so.0
/usr/lib64/libgtk-layer-shell.so.0.9.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gtk-layer-shell/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/gtk-layer-shell/657f3d1be67d6bd8b79692c3b22fed1d44c443c3
/usr/share/package-licenses/gtk-layer-shell/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
